### PR TITLE
regenerate with go1.12 and protoc 3.7.1

### PR DESCRIPTION
**Pull request by jmarais**
Regeneration with go1.12 and protoc 3.7.1.

This was just cloning the repo, running ```make```  and updating the travis config.

Edit: I seemed to push my url fix to the wrong branch. However If you are happy with both changes I will keep this request up. Let me know if you want to split the changes into two request.

We have an issue with the generation of the webform when there are specials characters present in the URL Variables. If you have a variable with a string containing "==" the splitting code will break up that string an create an invalid json object. The url parsing code will fail and an malformed webform will appear.
This ```getUrlParameter``` function was updated according to this SO discussion:
https://stackoverflow.com/a/8486188

### CODE REVIEW

**Comment by awalterschulze** [comment]
LGTM please merge

**Review by XavierMP14 — COMMENTED** [review]
Pull request

**Review by XavierMP14 — COMMENTED** [review]
X

**Comment by XavierMP14** [comment]
X

**Pull request merged**
