### PR TITLE
WithGZIPDecompressor

### PR DESCRIPTION
**Pull request by tgulacsi**
Enable to communicate with servers WithGZIPCompressor ServerOption.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Won't this allow only GZIPCompressed servers?

Have you looked at https://github.com/gogo/letmegrpc#customization

**Comment by tgulacsi** [comment]
The Decompressor allows speaking with servers either with or without a Compressor - decompresses only if the response is compressed. So, I don't see any con here (I've tried, and it works with a server without a Compressor).

**Comment by awalterschulze** [comment]
If this is the case, why is an option and not the default?

**Comment by tgulacsi** [comment]
Good question, I don't know. Less default dependency, less unneeded latency (checking whether the payload is compressed costs some time, I'm sure), and "explicit is better than implicit"?

As I see, Compressor and Decompressor are general interfaces, and only gzip has an implementation inside grpc, but it could use any other compression easily.

**Comment by awalterschulze** [comment]
I have tested it with these three commits
https://github.com/gogo/grpctests/commits/testingcompression

https://github.com/gogo/grpctests/commit/d59f6afb42b817e69b44905e99badf5fceda7630
https://github.com/gogo/grpctests/commit/b3bb96ce6703073a50652bc89d9ac1046ae8f690
https://github.com/gogo/grpctests/commit/96b270639800fc6f87ea2e5971e7fa3d954a2265

Seems like you are correct.

**Comment by awalterschulze** [comment]
I have also added a new authors file.  So you if you would like to have some copyright please add yourself to the AUTHORS file in this pullrequest.  Then I will merge.

**Comment by tgulacsi** [comment]
Thanks!

**Comment by awalterschulze** [comment]
No Thank you :)

**Pull request merged**
